### ISSUE TITLE
Images showing 404

### ISSUE THREAD

**Issue by ghost** [inviqa/mx-megamenu#27]
Images are not being rendered properly when using the insert image button. The image url appears as https://www.testme.com/%22https://www.testme.com/media/%22wysiwyg/cassette.jpg%22%22 

Magento 2.2.6

**Comment by kispali** [comment]
Hi jupiter01

Thank you for giving me feedback. I have checked that issue and it seems it is a default Magento 2 issue. I have tried the same in any cms page and it has inserted the following code snippet:
<img src="{{media url="https://hostname/media/wysiwyg/Elasticizer-How-To-2016_1.jpg"}}" /> which is incorrect as the hostname and media folder shouldn't be included. The {{media url=""}} directive converts the url based on the current host so in this case you will get the same: <img src="https://hostname"https://hostname/media/wysiwyg/Elasticizer-How-To-2016_1.jpg"" />. 
The wysiwyg editor what I use for this MegaMenu is the same default Magento 2 wysiwyg editor which is used anywhere else.
