### ISSUE TITLE
Remove PHP 7.0 dependency restriction

### ISSUE THREAD

**Issue by duffner** [inviqa/mx-megamenu#30]
Most Magento installations now run 7.1 or 7.2, I don't see anything in the code that would specifically break this, however, composer.json restricts.  Is this necessary / can be removed?

**Comment by tkotosz** [comment]
you are right , this module depends on the magento framework package which already defines the required php version so that requirement can be removed from the composer json

**Comment by kispali** [comment]
Fixed: https://github.com/inviqa/mx-megamenu/releases/tag/1.2.2
