### ISSUE TITLE
Unexpected identifier error when category name with apostrophe/single quote

### ISSUE THREAD

**Issue by gjportegies** [inviqa/mx-megamenu#32]
I'm having a couple of categories with an ' in their names like _Auto's_ (Dutch for cars).
This is causing an error in the `view/adminhtml/templates/editor.phtml` file on line 60 where the json is loaded in the javascrip:

`var menuItemsData = '<?php echo $menuJson; ?>';`

I already tried removing the single quotes from this line `var menuItemsData = <?php echo $menuJson; ?>;` and removing the decodeParams() method from the buildItems() method in the `megamenu-editor.js`. But this only solves the issue partially.

**Comment by kispali** [comment]
This is now fixed in this release: https://github.com/inviqa/mx-megamenu/releases/tag/1.2.4

**Comment by gjportegies** [comment]
Thanks @kispali
