### ISSUE TITLE
Add support for breadcrumbs on the category and product pages

### ISSUE THREAD

**Issue by jacs-inviqa** [inviqa/mx-megamenu#34]
See `vendor/magento/module-catalog/view/frontend/web/js/product/breadcrumbs.js` in default magento (and the other two breadcrumbs.js files too).

Vanilla Magento checks the browser referrer and the current url to generate breadcrumbs. It uses the titles and links in the Nav Menu. However when using a custom menu, this functionality silently breaks. 

Please support breadcrumbs with MenuMenu too. (by adding a custom breadcrumbs.js override possibly)

**Comment by kispali** [comment]
This is now fixed in this release: https://github.com/inviqa/mx-megamenu/releases/tag/1.2.4
